# kwanata.py reads this file.

# *************** KWANATA - KANATA configuration ******************

# KWanata injects a script in KDE that gets information about a windows
# whenever there is a change in whe window that its currently active.
# It will check then this cofiguration, to determine how to report to kanata.
# The first app matching is the one whose layer/virtual_keys are send
# to kanata.
#
# Format:

# [[app]]
# name = "name_of_app regex"          # Optional.
# class = "class_of_app regex"        # Optional.
# caption = "title_of_window regex"   # Optional.
# layer = "kanata_layer_name"         # Optional.
# virtual_keys = ["vk1", "vk2", ...]  # Optional.
#
# name, class and caption are used to match the info of the current active 
# window. layer and virtual_keys are sent to kanata if a match is detected.
#
# If more than one field to match is present, they all need to match.

[[app]]
name = "chrome"
caption = "@Colab"
virtual_keys = ["vk_colab", "vk_chrome"]

[[app]]
name = "chrome"
virtual_keys = ["vk_chrome"]

[[app]]
name = "firefox"
class = "firefoxColab"
virtual_keys = ["vk_colab", "vk_firefox"]

[[app]]
name = "firefox"
virtual_keys = ["vk_firefox"]

[[app]]
name = "obsidian"
virtual_keys = ["vk_obsidian"]

[[app]]
name = "soffice.bin"
virtual_keys = ["vk_okular"]

[[app]]
name = "foot"
caption = "^tmux.*(N|n)vim$"
virtual_keys = ["vk_nvim", "vk_tmux"]

[[app]]
name = "foot"
caption = "^tmux"
virtual_keys = ["vk_tmux", "vk_foot"]

[[app]]
name = "foot"
caption = "^Zellij"
virtual_keys = ["vk_zellij", "vk_foot"]

[[app]]
name = "foot"
caption = "(N|n)vim$"
virtual_keys = ["vk_nvim"]

[[app]]
name = "konsole"
caption = "zellij — Konsole$"
virtual_keys = ["vk_zellij"]

[[app]]
name = "konsole"
caption = "nvim — Konsole$"
virtual_keys = ["vk_nvim"]

[[app]]
name = "foot|konsole"
virtual_keys = ["vk_foot"]

[[app]]
name = "dolphin"
virtual_keys = ["vk_dolphin"]

[[app]]
caption = "(All Files|Save File — Skanpage|Select files)"
virtual_keys = ["vk_dolphin"]

[[app]]
class = "libreoffice-calc"
virtual_keys = ["vk_calc"]

[[app]]
class = "com.rtosta.zapzap"
virtual_keys = ["vk_zapzap"]


[[app]]
class = "kiwix"
virtual_keys = ["vk_kiwix"]


# *************** KWANATA - Run Or Raise configuration ******************

# Run-or-raise: triggered by Kanata push-msg "APP: <name>"
# [[run_or_raise]] could  have these fields:
# name -- Name of the app (required). 
# class -- App's class (optional). It is a regex. It will be use to search 
#          if the app is running.
# caption -- App's caption (optional). It is a regex. It will be use to 
#            search if the app is running.
# command -- Command to launch the app (if omitted, name will be used as 
#            command). It the app is not running command will run.
#
# Defaults: class="", caption="", command=name.
# NOTE: At least caption or class should be defined to reach and app.

# Chrome app - Mgmt window 
[[run_or_raise]]
name = "chromeMgmt"
class = "google-chrome"
caption = "chromeMgmt"
command = "google-chrome-stable --new-window --window-name='chromeMgmt' https://mail.google.com https://contacts.google.com https://calendar.google.com"

# Chrome app - Cloud window 
[[run_or_raise]]
name = "chromeCloud"
class = "google-chrome"
caption = "chromeCloud"
command = "google-chrome-stable --new-window --window-name='chromeCloud' https://guacimara.synology.me:8981/ https://medano.synology.me:8981/ https://perseo:8384/ https://guacimara:8384/"

# Chrome app - AI window 
[[run_or_raise]]
name = "chromeAI"
class = "google-chrome"
caption = "chromeAI"
command = "google-chrome-stable --new-window --window-name='chromeAI' https://chatgpt.com/ https://gemini.google.com/ https://claude.ai/ https://notebooklm.google.com/"

# Chrome app - Banks window 
[[run_or_raise]]
name = "chromeBanks"
class = "google-chrome"
caption = "chromeBanks"
command = "google-chrome-stable --new-window --window-name='chromeBanks' https://particulares.bancosantander.es/oneweb/ https://bancaonline.bankinter.com/gestion/login.xhtml https://www.caixabank.es/particular/home/particulares_es.html https://www.arquia.com/es-es/ https://www.revolut.com/"

# Chrome app - Misc window 
[[run_or_raise]]
name = "chromeMisc1"
class = "google-chrome"
caption = "chromeMisc1"
command = "google-chrome-stable --new-window --window-name='chromeMisc1'"

# Chrome app - Misc window 
[[run_or_raise]]
name = "chromeMisc2"
class = "google-chrome"
caption = "chromeMisc2"
command = "google-chrome-stable --new-window --window-name='chromeMisc2'"

# Chrome app - Misc window 
[[run_or_raise]]
name = "chromeMisc3"
class = "google-chrome"
caption = "chromeMisc3"
command = "google-chrome-stable --new-window --window-name='chromeMisc3'"

# Chrome app - Misc window 
[[run_or_raise]]
name = "chromeMisc4"
class = "google-chrome"
caption = "chromeMisc4"
command = "google-chrome-stable --new-window --window-name='chromeMisc4'"

[[run_or_raise]]
name = "chromeColab"
class = "google-chrome"
caption = "chromeColab"
command = "google-chrome-stable --new-window --window-name='chromeColab' https://colab.research.google.com/"

# Chrome app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "chrome"
class = "google-chrome"
command = "google-chrome-stable"

# Firefox app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "firefoxMgmt"
class = "firefoxMgmt"
command = "firefox -P mgmt --no-remote --name='firefoxMgmt' https://mail.google.com https://contacts.google.com https://calendar.google.com"

# Firefox app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "firefoxCloud"
class = "firefoxCloud"
command = "firefox -P cloud --no-remote --name='firefoxCloud' https://192.168.1.10:8981/ https://perseo:8384/ https://guacimara:8384/"

# Firefox app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "firefoxAI"
class = "firefoxAI"
command = "firefox -P AI --no-remote --name='firefoxAI' https://chatgpt.com/ https://gemini.google.com/ https://claude.ai/ https://notebooklm.google.com/"

# Firefox app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "firefoxBanks"
class = "firefoxBanks"
command = "firefox -P banks --no-remote --name='firefoxBanks' https://particulares.bancosantander.es/oneweb/ https://bancaonline.bankinter.com/gestion/login.xhtml https://www.caixabank.es/particular/home/particulares_es.html https://www.arquia.com/es-es/ https://www.revolut.com/"

# Firefox app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "firefoxMisc"
class = "firefoxMisc"
command = "firefox -P misc --no-remote --name='firefoxMisc'"

# Firefox app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "firefoxColab"
class = "firefoxColab"
command = "firefox -P colab --no-remote --name='firefoxColab' https://colab.research.google.com/"

# Firefox app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "firefox"
class = "firefox"
command = "firefox -P default-release --no-remote --name='firefox'"

# Obsidian app - When raised multiple times it will iterate through opened obsidians.
[[run_or_raise]]
name = "obsidian"
class = "obsidian"
command = "~/.local/bin/appimages/obsidian.AppImage --no-sandbox"

# Okular app - When raised multiple times it will iterate through opened okular.
[[run_or_raise]]
name = "okular"
class = "okular|org.kde.okular"
command = "okular"

# Libreoffice Calc app - When raised multiple times it will iterate through opened Calc.
[[run_or_raise]]
name = "calc"
class = "libreoffice-calc"
command = "libreoffice"

# Terminal app (foot) - When raised multiple times it will iterate through opened terminal windows.
[[run_or_raise]]
name = "terminal"
class = "foot"
# Don't want to iterate through terminal windows where nvim or claude code is running.
caption = "^((?!(nvim|claude code)).)*$"

# Nvim app - When raised multiple times it will iterate through opened nvims.
[[run_or_raise]]
name = "nvim"
# It will find Nvim running inside foot or Konsole (checking for the signature in its title) or as a stand alone app.
caption = "(Nvim|nvim — Konsole)$"
command = "nvim"

# Claude Code app - When raised multiple times it will iterate through opened claude code apps.
[[run_or_raise]]
name = "claude_code"
# Claude Code will run inside of a terminal. It will check the signature in it's title.
caption = "Claude Code$"
command = "foot"

# File Explorer app (dolphin) - When raised multiple times it will iterate through opened file explorers.
[[run_or_raise]]
name = "fileexplorer"
class = "org.kde.dolphin"
command = "dolphin"

# KeePassXC app - When raised multiple times it will iterate through opened file explorers.
[[run_or_raise]]
name = "keepassxc"
class = "org.keepassxc.KeePassXC"
command = "keepassxc"

[[run_or_raise]]
name = "zapzap"
class = "zapzap"
command = "zapzap"

[[run_or_raise]]
name = "telegram"
class = "org.telegram"
command = "telegram"

[[run_or_raise]]
name = "fusion360"
caption = "Autodesk Fusion"
command = "env 'WINEPREFIX=/home/juan/.autodesk_fusion/wineprefixes/default' wine 'C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\Autodesk\\\\Autodesk Fusion.lnk'"

[[run_or_raise]]
name = "sketchup"
caption = "SketchUp for Web"
command = "/opt/google/chrome/google-chrome --profile-directory=Default --app-id=beodkchghmjjfhojholjdhdfodleinln"

[[run_or_raise]]
name = "orcaslicer"
class = "OrcaSlicer"
command = "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=entrypoint --file-forwarding com.orcaslicer.OrcaSlicer"

[[run_or_raise]]
name = "onlyoffice"
class = "ONLYOFFICE"
command = "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=desktopeditors --file-forwarding org.onlyoffice.desktopeditors"
